// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDinY3lBTmJpOr4-zsqptDgCtGyiHG0gI8',
    appId: '1:529773385078:web:6b91cec9efafbffb105657',
    messagingSenderId: '529773385078',
    projectId: 'silver-clinics',
    authDomain: 'silver-clinics.firebaseapp.com',
    storageBucket: 'silver-clinics.appspot.com',
    measurementId: 'G-D414FXM0GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHJADHZQpjPNrMUSpg54tJ0cLwycaRLz8',
    appId: '1:529773385078:android:1358abf757c12340105657',
    messagingSenderId: '529773385078',
    projectId: 'silver-clinics',
    storageBucket: 'silver-clinics.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2uRAiVJ2341Ee_JkQsUjt3QLObJ1R0BA',
    appId: '1:529773385078:ios:5b27b375fbec2363105657',
    messagingSenderId: '529773385078',
    projectId: 'silver-clinics',
    storageBucket: 'silver-clinics.appspot.com',
    iosBundleId: 'com.example.silverClinics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2uRAiVJ2341Ee_JkQsUjt3QLObJ1R0BA',
    appId: '1:529773385078:ios:5b27b375fbec2363105657',
    messagingSenderId: '529773385078',
    projectId: 'silver-clinics',
    storageBucket: 'silver-clinics.appspot.com',
    iosBundleId: 'com.example.silverClinics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDinY3lBTmJpOr4-zsqptDgCtGyiHG0gI8',
    appId: '1:529773385078:web:a3a6aabf7623b713105657',
    messagingSenderId: '529773385078',
    projectId: 'silver-clinics',
    authDomain: 'silver-clinics.firebaseapp.com',
    storageBucket: 'silver-clinics.appspot.com',
    measurementId: 'G-CCGFNK3G9K',
  );
}
